.PHONY: i8080_util_tb
i8080_util_tb:
	xelab --prj prj/i8080_util_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_util_tb

.PHONY: get_inst_test_tb
get_inst_test_tb:
	xelab --prj prj/get_inst_test_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.get_inst_test_tb

.PHONY: i8080_microcode_tb
i8080_microcode_tb:
	xelab --prj prj/i8080_microcode_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_microcode_tb

.PHONY: i8080_microcode_controller_tb
i8080_microcode_controller_tb:
	xelab --prj prj/i8080_microcode_controller_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_microcode_controller_tb

.PHONY: i8080_core_tb
i8080_core_tb:
	xelab --prj prj/i8080_core_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_core_tb

.PHONY: i8080_nb_inst_nop_tb
i8080_nb_inst_nop_tb:
	xelab --prj prj/i8080_nb_inst_nop_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_nb_inst_nop_tb

.PHONY: i8080_memory_sim_tb
i8080_memory_sim_tb:
	xelab --prj prj/i8080_memory_sim_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_memory_sim_tb

.PHONY: i8080_core_inst_NOP_tb
i8080_core_inst_NOP_tb:
	xelab --prj prj/i8080_core_inst_NOP_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_core_inst_NOP_tb

.PHONY: i8080_core_inst_LXI_tb
i8080_core_inst_LXI_tb:
	xelab --prj prj/i8080_core_inst_LXI_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_core_inst_LXI_tb

.PHONY: i8080_address_unit_tb
i8080_address_unit_tb:
	xelab --prj prj/i8080_address_unit_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_address_unit_tb

.PHONY: i8080_register_file_tb
i8080_register_file_tb:
	xelab --prj prj/i8080_register_file_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_register_file_tb

.PHONY: i8080_alu_util_tb
i8080_alu_util_tb:
	xelab --prj prj/i8080_alu_util_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_alu_util_tb

.PHONY: i8080_alu_tb
i8080_alu_tb:
	xelab --prj prj/i8080_alu_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_alu_tb

.PHONY: i8080_core_hw_int_tb
i8080_core_hw_int_tb:
	xelab --prj prj/i8080_core_hw_int_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_core_hw_int_tb

.PHONY: ssd_mm_device_tb
ssd_mm_device_tb:
	xelab --prj prj/ssd_mm_device_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.ssd_mm_device_tb

.PHONY: kbd_mm_device_tb
kbd_mm_device_tb:
	xelab --prj prj/kbd_mm_device_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.kbd_mm_device_tb

.PHONY: sysmem_device_tb
sysmem_device_tb:
	xelab --prj prj/sysmem_device_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.sysmem_device_tb

.PHONY: i8080_system_test_tb
i8080_system_test_tb:
	xelab --prj prj/i8080_system_test_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.i8080_system_test_tb

